services:
  - type: web
    name: yt-server
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && pip install yt-dlp
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
